from .registration import *
from .new_user import *
from .contracts import *
from .check_registration import *
from .data_for_security import *
from .set_referral import *
from .referral_system_info import *
from .order import *
from .block_user import *
from .stats import *
from .change_city import *
from .verif_codes import *
from .rating import *
from .payments import *
from .balance import *
from .wallet_payments import *
from .max_integration import *
from .acts import *
from .receipts import *
